"$schema" = 'https://starship.rs/config-schema.json'

[conda]
  ignore_base = false

[gcloud]
  symbol = ''
  format = '[$symbol$active]($style) '

[git_commit]
  tag_disabled = false

[kubernetes]
  disabled = false
